"""Standardize manuscript figure exports for the IEEE Access package.

Source-backed plots are generated by their owning scripts. For legacy figures
where only a PNG asset is present in the private paper folder, this script emits
a PDF companion at IEEE column/full-column dimensions and records that the PDF
contains embedded raster content. This keeps the Overleaf package consistent
while making the provenance explicit.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from visualization.build_architecture_figure import build as build_architecture

PAPER = ROOT / "paper" / "ieee_access_overleaf"
FIGURES = PAPER / "figures"
REGISTRY = ROOT / "results" / "registry.json"
MANIFEST = ROOT / "results" / "figure_manifest.json"

COLUMN_WIDTH_IN = 3.5
FULL_WIDTH_IN = 7.16
TARGET_DPI = 300

FULL_WIDTH_NAMES = {"architecture"}


def png_to_pdf(path: Path) -> dict[str, object]:
    image = mpimg.imread(path)
    height_px, width_px = image.shape[:2]
    width_in = FULL_WIDTH_IN if path.stem in FULL_WIDTH_NAMES else COLUMN_WIDTH_IN
    height_in = width_in * height_px / width_px

    fig = plt.figure(figsize=(width_in, height_in))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.imshow(image)
    ax.axis("off")
    out = path.with_suffix(".pdf")
    fig.savefig(out, dpi=TARGET_DPI)
    plt.close(fig)
    return {
        "name": path.stem,
        "source": str(path.relative_to(ROOT)),
        "pdf": str(out.relative_to(ROOT)),
        "width_in": width_in,
        "dpi": TARGET_DPI,
        "content": "embedded_raster",
    }


def main() -> int:
    FIGURES.mkdir(parents=True, exist_ok=True)
    if REGISTRY.exists():
        build_architecture(REGISTRY, FIGURES / "architecture.pdf")

    manifest: list[dict[str, object]] = []
    for pdf in sorted(FIGURES.glob("*.pdf")):
        png = pdf.with_suffix(".png")
        manifest.append(
            {
                "name": pdf.stem,
                "source": str((png if png.exists() else pdf).relative_to(ROOT)),
                "pdf": str(pdf.relative_to(ROOT)),
                "width_in": FULL_WIDTH_IN if pdf.stem in FULL_WIDTH_NAMES else COLUMN_WIDTH_IN,
                "content": "vector_or_source_pdf",
            }
        )

    existing = {entry["name"] for entry in manifest}
    for png in sorted(FIGURES.glob("*.png")):
        if png.stem in existing:
            continue
        manifest.append(png_to_pdf(png))

    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST}")
    print(f"standardized {len(manifest)} figures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
