"""Lint paper table/caption numbers against the registry and generated macros.

The check is intentionally scoped to claim-bearing locations: table cells and
figure captions. It ignores LaTeX layout dimensions, citation years, version
numbers, and command names. The goal is to catch stale hard-coded result values
without turning ordinary prose into a false-positive minefield.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
NUMBER_RE = re.compile(r"(?<![A-Za-z0-9.])[-+]?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?%?(?![A-Za-z0-9.])")
MACRO_RE = re.compile(r"\\newcommand\{\\([A-Za-z][A-Za-z0-9]*)\}\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}")
CAPTION_RE = re.compile(r"\\caption(?:\[[^\]]*\])?\{(?P<body>(?:[^{}]|\{[^{}]*\})*)\}", re.S)
TABLE_RE = re.compile(r"\\begin\{tabular\}.*?\\end\{tabular\}", re.S)


@dataclass(frozen=True)
class Finding:
    path: Path
    line: int
    literal: str
    context: str


def normalize_number(text: str) -> set[str]:
    raw = text.strip()
    is_percent = raw.endswith("%") or raw.endswith(r"\%")
    raw = raw.replace(",", "").replace(r"\%", "").rstrip("%")
    try:
        val = float(raw)
    except ValueError:
        return {text}

    out = {raw, str(int(val)) if val.is_integer() else f"{val:.12g}"}
    if is_percent:
        out.add(f"{val:.12g}%")
        out.add(f"{val/100:.12g}")
    else:
        out.add(f"{val:.12g}")
        out.add(f"{val*100:.12g}%")
    if val.is_integer():
        out.add(f"{int(val):,}")
    return out


def line_for_offset(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def strip_latex(text: str) -> str:
    text = re.sub(r"\\cite\{[^}]*\}", "", text)
    text = re.sub(r"\\ref\{[^}]*\}", "", text)
    text = re.sub(r"\\label\{[^}]*\}", "", text)
    text = re.sub(r"\\includegraphics(?:\[[^\]]*\])?\{[^}]*\}", "", text)
    text = re.sub(r"\\(?:texttt|textbf|emph|url)\{([^{}]*)\}", r"\1", text)
    text = re.sub(r"\\[A-Za-z]+\*?(?:\[[^\]]*\])?", " ", text)
    return text


def likely_non_claim(literal: str, context: str) -> bool:
    raw = literal.replace(",", "")
    ctx = context.lower()
    if "tabular}{p{" in ctx or "linewidth" in ctx or "textwidth" in ctx:
        return True
    if re.search(r"\bt\d{4}", ctx) or re.search(r"\bv(?:13|14|15)\.1\b", ctx):
        return True
    if raw == "95" and "ci" in ctx:
        return True
    if re.search(r"\b(v|version)\s*" + re.escape(raw), ctx):
        return True
    if re.search(r"\b(19|20)\d{2}\b", raw):
        return True
    if raw in {"0", "1", "2", "3", "4", "5"} and any(
        word in ctx for word in ["rq", "from 1", "to 5", "five-point", "top-", "gpt-4", "v13", "v14", "v15"]
    ):
        return True
    if "gpt-4" in ctx and raw in {"4", "1"}:
        return True
    return False


def registry_values(path: Path) -> set[str]:
    if not path.exists():
        return set()
    data = json.loads(path.read_text(encoding="utf-8"))
    allowed: set[str] = set()
    for entry in data.values():
        if not isinstance(entry, dict):
            continue
        for key in ("value", "n", "ci", "p"):
            value = entry.get(key)
            if isinstance(value, list):
                for item in value:
                    allowed.update(normalize_number(str(item)))
            elif value is not None:
                allowed.update(normalize_number(str(value)))
    return allowed


def macro_values(paths: list[Path]) -> set[str]:
    allowed: set[str] = set()
    for path in paths:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for _name, body in MACRO_RE.findall(text):
            body = body.replace(r"\%", "%")
            for match in NUMBER_RE.finditer(body):
                allowed.update(normalize_number(match.group(0)))
    return allowed


def claim_regions(path: Path) -> list[tuple[int, str]]:
    text = path.read_text(encoding="utf-8")
    if "Auto-generated by" in text:
        return []
    regions: list[tuple[int, str]] = []
    for regex in (CAPTION_RE, TABLE_RE):
        for match in regex.finditer(text):
            regions.append((match.start(), match.group(0)))
    return regions


def lint_file(path: Path, allowed: set[str]) -> list[Finding]:
    text = path.read_text(encoding="utf-8")
    findings: list[Finding] = []
    for start, region in claim_regions(path):
        clean = strip_latex(region)
        for match in NUMBER_RE.finditer(clean):
            literal = match.group(0)
            context = clean[max(0, match.start() - 80) : match.end() + 80]
            if likely_non_claim(literal, context):
                continue
            if normalize_number(literal).isdisjoint(allowed):
                findings.append(
                    Finding(
                        path=path,
                        line=line_for_offset(text, start),
                        literal=literal,
                        context=" ".join(context.split()),
                    )
                )
    return findings


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--paper", type=Path, default=ROOT / "paper" / "ieee_access_overleaf")
    parser.add_argument("--registry", type=Path, default=ROOT / "results" / "registry.json")
    parser.add_argument(
        "--macros",
        type=Path,
        action="append",
        default=[],
        help="Generated macro file. Can be supplied multiple times.",
    )
    parser.add_argument("--allow", action="append", default=[], help="Extra allowed literal value.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    if not args.paper.exists():
        print(f"number-consistency: skipped missing paper directory {args.paper}")
        return 0

    macro_paths = args.macros or [args.paper / "generated_macros.tex", ROOT / "paper" / "generated_macros.tex"]
    allowed = registry_values(args.registry) | macro_values(macro_paths)
    for item in args.allow:
        allowed.update(normalize_number(item))
    # Design constants and ATT&CK version labels that are not result claims.
    for item in ["48", "4", "3", "2", "5", "6", "8,821", "13.1", "14.1", "15.1", "0.7", "0.95", "42"]:
        allowed.update(normalize_number(item))

    tex_files = [p for p in args.paper.glob("*.tex") if p.name != "references.bib"]
    findings = [finding for path in tex_files for finding in lint_file(path, allowed)]
    if findings:
        print("number-consistency: FAIL")
        for finding in findings:
            rel = finding.path.relative_to(ROOT) if finding.path.is_relative_to(ROOT) else finding.path
            print(f"{rel}:{finding.line}: {finding.literal} not in registry/macros :: {finding.context}")
        return 1
    print(f"number-consistency: ok ({len(tex_files)} tex files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
