"""Audit overlap between generated chains and public ATT&CK group procedures."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "mitre" / "enterprise-attack-14.1-active-techniques.json"
DEFAULT_CORPUS = ROOT / "data" / "generated" / "scaleup" / "adversim_scaleup_full.jsonl"
RESULTS = ROOT / "results" / "contamination_audit.json"
TABLE = ROOT / "paper" / "ieee_access_overleaf" / "table_contamination_audit.tex"


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            rows.append(json.loads(obj) if isinstance(obj, str) else obj)
    return rows


def chain(row: dict[str, Any]) -> list[str]:
    tids = []
    for stage in row.get("attack_stages", []) or []:
        for tech in stage.get("techniques", []) or []:
            tid = str(tech.get("technique_id", "")).upper()
            if tid:
                tids.append(tid)
    return list(dict.fromkeys(tids))


def jaccard(a: set[str], b: set[str]) -> float:
    return len(a & b) / max(1, len(a | b))


def write_table(result: dict[str, Any]) -> None:
    lines = [
        "% Auto-generated by analysis/contamination_audit.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Generated-chain overlap with public ATT\\&CK group procedure sets.}",
        "\\label{tab:contamination-audit}",
        "\\small",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Audit metric & Value \\\\",
        "\\midrule",
        f"Generated scenarios audited & {result['n_scenarios']} \\\\",
        f"Exact ATT\\&CK group-set matches & {result['exact_set_matches']} \\\\",
        f"Generated chains subset of a group set & {result['subset_matches']} \\\\",
        f"High-overlap chains (Jaccard $\\geq {result['high_jaccard_threshold']:.2f}$) & {result['high_jaccard_matches']} \\\\",
        f"Maximum observed Jaccard & {result['max_jaccard']:.3f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    TABLE.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--threshold", type=float, default=0.80)
    args = parser.parse_args()
    rows = load_jsonl(args.corpus)
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    groups = {
        group: set(tids)
        for group, tids in index.get("group_techniques", {}).items()
        if isinstance(tids, list) and tids
    }
    exact = subset = high = 0
    max_j = 0.0
    max_examples: list[dict[str, Any]] = []
    for row in rows:
        tids = set(chain(row))
        if not tids:
            continue
        best_group = None
        best_j = 0.0
        exact_hit = subset_hit = high_hit = False
        for group, group_tids in groups.items():
            if tids == group_tids:
                exact_hit = True
            if tids.issubset(group_tids):
                subset_hit = True
            score = jaccard(tids, group_tids)
            if score > best_j:
                best_j = score
                best_group = group
        high_hit = best_j >= args.threshold
        exact += int(exact_hit)
        subset += int(subset_hit)
        high += int(high_hit)
        if best_j > max_j:
            max_j = best_j
            max_examples = [
                {
                    "scenario_id": row.get("scenario_id"),
                    "best_group": best_group,
                    "jaccard": round(best_j, 6),
                    "technique_count": len(tids),
                }
            ]
    result = {
        "schema_version": 1,
        "source": str(args.corpus),
        "n_scenarios": len(rows),
        "group_sets": len(groups),
        "high_jaccard_threshold": args.threshold,
        "exact_set_matches": exact,
        "subset_matches": subset,
        "high_jaccard_matches": high,
        "max_jaccard": round(max_j, 6),
        "max_examples": max_examples,
        "interpretation": (
            "Overlap with public ATT&CK procedure sets is a contamination and construct-validity threat. "
            "Low exact/high-overlap rates reduce, but do not eliminate, memorization concern because model "
            "training data are not observable."
        ),
    }
    RESULTS.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_table(result)
    print(f"wrote {RESULTS}")
    print(f"wrote {TABLE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
