"""Corpus diversity audit using n-gram Jaccard near-duplicate rates."""

from __future__ import annotations

import argparse
import json
import math
import random
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CORPUS = ROOT / "data" / "generated" / "scaleup" / "adversim_scaleup_full.jsonl"
FALLBACK_CORPUS = ROOT / "dataset" / "samples" / "scaleup_sample.jsonl"
RESULTS = ROOT / "results" / "corpus_diversity.json"
TABLE = ROOT / "paper" / "ieee_access_overleaf" / "table_corpus_diversity.tex"
FIGURE = ROOT / "paper" / "ieee_access_overleaf" / "figures" / "corpus_diversity_histogram.pdf"


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            rows.append(json.loads(obj) if isinstance(obj, str) else obj)
    return rows


def scenario_text(row: dict[str, Any]) -> str:
    chunks = [str(row.get("narrative", ""))]
    for stage in row.get("attack_stages", []) or []:
        chunks.append(str(stage.get("stage_name", "")))
        chunks.append(str(stage.get("description", "")))
        for tech in stage.get("techniques", []) or []:
            chunks.append(str(tech.get("technique_id", "")))
            chunks.append(str(tech.get("technique_name", "")))
    return " ".join(chunks).lower()


def ngrams(text: str, n: int) -> set[str]:
    toks = re.findall(r"[a-z0-9]+", text.lower())
    if len(toks) < n:
        return {" ".join(toks)} if toks else set()
    return {" ".join(toks[i : i + n]) for i in range(len(toks) - n + 1)}


def jaccard(a: set[str], b: set[str]) -> float:
    if not a and not b:
        return 1.0
    return len(a & b) / max(1, len(a | b))


def sample_pairs(n: int, max_pairs: int, rng: random.Random) -> list[tuple[int, int]]:
    total = n * (n - 1) // 2
    if total <= max_pairs:
        return [(i, j) for i in range(n) for j in range(i + 1, n)]
    pairs = set()
    while len(pairs) < max_pairs:
        i = rng.randrange(n)
        j = rng.randrange(n)
        if i == j:
            continue
        if i > j:
            i, j = j, i
        pairs.add((i, j))
    return sorted(pairs)


def audit_group(rows: list[dict[str, Any]], sets: list[set[str]], indices: list[int], threshold: float, max_pairs: int, rng: random.Random) -> dict[str, Any]:
    pairs = sample_pairs(len(indices), max_pairs, rng)
    scores = [jaccard(sets[indices[i]], sets[indices[j]]) for i, j in pairs]
    near = sum(1 for s in scores if s >= threshold)
    return {
        "n": len(indices),
        "pairs_evaluated": len(scores),
        "near_duplicate_pairs": near,
        "near_duplicate_rate": round(near / max(1, len(scores)), 6),
        "mean_jaccard": round(sum(scores) / max(1, len(scores)), 6),
        "p95_jaccard": round(sorted(scores)[int(0.95 * (len(scores) - 1))], 6) if scores else None,
        "max_jaccard": round(max(scores), 6) if scores else None,
    }


def estimated_effective_unique(n: int, near_duplicate_rate: float) -> int:
    """Estimate effective unique count from sampled pair near-duplicate rate.

    A full greedy clustering pass is quadratic and slow on the 5k corpus. The
    sampled estimate is conservative enough for a CI diversity audit while
    keeping the target runnable on reviewer machines.
    """

    return max(1, round(n * (1.0 - near_duplicate_rate)))


def write_table(result: dict[str, Any], path: Path) -> None:
    rows = result["per_attack_type"]
    threshold = result["threshold"]
    lines = [
        "% Auto-generated by analysis/corpus_diversity.py",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Corpus diversity audit aggregated by attack type. Near-duplicate threshold: 5-gram Jaccard $\\geq {threshold:.2f}$.}}",
        "\\label{tab:corpus-diversity}",
        "\\small",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Attack type & Scenarios & Near-dup. rate & Mean Jaccard & Max Jaccard \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(f"{row['attack_type']} & {row['n']} & {row['near_duplicate_rate']:.3f} & {row['mean_jaccard']:.3f} & {row['max_jaccard']:.3f} \\\\")
    lines.extend(["\\midrule", f"Global & {result['global']['n']} & {result['global']['near_duplicate_rate']:.3f} & {result['global']['mean_jaccard']:.3f} & {result['global']['max_jaccard']:.3f} \\\\", "\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_hist(scores: list[float], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(3.5, 2.4))
    ax.hist(scores, bins=30, color="#3b6ea8", edgecolor="white")
    ax.set_xlabel("Sampled pair 5-gram Jaccard")
    ax.set_ylabel("Pairs")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(path)
    fig.savefig(path.with_suffix(".png"), dpi=300)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS if DEFAULT_CORPUS.exists() else FALLBACK_CORPUS)
    parser.add_argument("--threshold", type=float, default=0.85)
    parser.add_argument("--ngram", type=int, default=5)
    parser.add_argument("--max-pairs", type=int, default=20000)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    rng = random.Random(args.seed)
    rows = load_jsonl(args.corpus)
    sets = [ngrams(scenario_text(row), args.ngram) for row in rows]
    global_pairs = sample_pairs(len(rows), args.max_pairs, rng)
    global_scores = [jaccard(sets[i], sets[j]) for i, j in global_pairs]
    global_result = audit_group(rows, sets, list(range(len(rows))), args.threshold, args.max_pairs, rng)
    global_result["effective_unique_count"] = estimated_effective_unique(len(rows), global_result["near_duplicate_rate"])

    groups: dict[str, list[int]] = defaultdict(list)
    for idx, row in enumerate(rows):
        cell = f"{row.get('attack_type','?')} / {row.get('environment_type','?')} / {row.get('difficulty','?')}"
        groups[cell].append(idx)
    per_cell = []
    for cell, indices in sorted(groups.items()):
        item = audit_group(rows, sets, indices, args.threshold, min(args.max_pairs, 5000), rng)
        item["cell"] = cell
        per_cell.append(item)

    attack_groups: dict[str, list[int]] = defaultdict(list)
    for idx, row in enumerate(rows):
        attack_groups[str(row.get("attack_type", "?"))].append(idx)
    per_attack_type = []
    for attack_type, indices in sorted(attack_groups.items()):
        item = audit_group(rows, sets, indices, args.threshold, min(args.max_pairs, 10000), rng)
        item["attack_type"] = attack_type
        per_attack_type.append(item)

    result = {
        "schema_version": 1,
        "source": str(args.corpus),
        "threshold": args.threshold,
        "ngram": args.ngram,
        "global": global_result,
        "per_attack_type": per_attack_type,
        "per_cell": per_cell,
    }
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    RESULTS.write_text(json.dumps(result, indent=2), encoding="utf-8")
    write_table(result, TABLE)
    write_hist(global_scores, FIGURE)
    print(f"wrote {RESULTS}")
    print(f"wrote {TABLE}")
    print(f"wrote {FIGURE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
