"""Emit a macro-wired LaTeX table from results/multimodel.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN = ROOT / "results" / "multimodel.json"
DEFAULT_OUT = ROOT / "paper" / "ieee_access_overleaf" / "table_multimodel_validation.tex"


def pct(value: Any) -> str:
    return f"{float(value) * 100:.1f}\\%"


def build_table(data: dict[str, Any]) -> str:
    lines = [
        "% Auto-generated by analysis/multimodel_table.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Exact-size multi-model validation replication generated from source results.}",
        "\\label{tab:multimodel}",
        "\\small",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Model & Accepted & First-attempt active & Active IDs & Base techniques & Base coverage \\\\",
        "\\midrule",
    ]
    for row in data.get("model_rows", []):
        if row.get("status") != "completed":
            continue
        ci = row.get("first_attempt_active_rate_wilson_95ci") or [None, None]
        ci_text = f"{pct(row['first_attempt_active_rate'])} [{pct(ci[0])}, {pct(ci[1])}]" if ci[0] is not None else pct(row["first_attempt_active_rate"])
        lines.append(
            f"{row['model']} & {row['n_accepted']} & {ci_text} & "
            f"{row['unique_active_v14_ids']} & {row['unique_base_techniques']} & "
            f"{pct(row['base_technique_coverage'])} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_IN)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    data = json.loads(args.input.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_table(data), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
