"""Template + ATT&CK-constrained random baseline for scenario generation."""

from __future__ import annotations

import argparse
import json
import random
from itertools import combinations
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "mitre" / "enterprise-attack-14.1-active-techniques.json"
RESULTS = ROOT / "results" / "non_llm_baseline.json"
TABLE = ROOT / "paper" / "ieee_access_overleaf" / "table_non_llm_baseline.tex"


TACTICS = [
    "reconnaissance",
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "defense-evasion",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]


def load_index() -> dict[str, Any]:
    return json.loads(INDEX.read_text(encoding="utf-8"))


def primary_tactic(meta: dict[str, Any]) -> str:
    tactics = meta.get("tactics") or []
    return tactics[0] if tactics else "unknown"


def group_pairs(index: dict[str, Any], active: set[str]) -> set[tuple[str, str]]:
    pairs = set()
    for tids in index.get("group_techniques", {}).values():
        clean = sorted({tid for tid in tids if tid in active})
        for a, b in combinations(clean, 2):
            pairs.add(tuple(sorted((a, b))))
    return pairs


def score(tids: list[str], active: set[str], pairs: set[tuple[str, str]]) -> float:
    v = sum(1 for tid in tids if tid in active) / max(1, len(tids))
    g = 1.0
    adj = [tuple(sorted((a, b))) for a, b in zip(tids, tids[1:]) if a != b]
    c = sum(1 for pair in adj if pair in pairs) / max(1, len(adj))
    return round(0.4 * v + 0.35 * g + 0.25 * c, 6)


def generate(n: int, seed: int, index: dict[str, Any]) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    active = set(index["active"])
    by_tactic: dict[str, list[str]] = {}
    for tid, meta in index["active"].items():
        by_tactic.setdefault(primary_tactic(meta), []).append(tid)
    rows = []
    for i in range(n):
        tactic_path = sorted(rng.sample(TACTICS, k=4), key=TACTICS.index)
        tids = [rng.choice(by_tactic.get(tactic, sorted(active))) for tactic in tactic_path]
        stages = [
            {
                "stage_name": tactic.replace("-", " ").title(),
                "description": f"Template baseline stage mapped to {tid}.",
                "techniques": [{"technique_id": tid, "technique_name": index["active"][tid].get("name", tid)}],
            }
            for tactic, tid in zip(tactic_path, tids)
        ]
        rows.append(
            {
                "scenario_id": f"template-baseline-{i+1:04d}",
                "attack_type": "Template Baseline",
                "environment_type": "Enterprise Network",
                "difficulty": "Medium",
                "narrative": "Template-generated ATT&CK-constrained scenario baseline.",
                "attack_stages": stages,
                "attack_graph": {"edges": [[stages[j]["stage_name"], stages[j + 1]["stage_name"]] for j in range(len(stages) - 1)]},
            }
        )
    return rows


def summarize(rows: list[dict[str, Any]], index: dict[str, Any]) -> dict[str, Any]:
    active = set(index["active"])
    pairs = group_pairs(index, active)
    all_tids = [
        tech["technique_id"]
        for row in rows
        for stage in row["attack_stages"]
        for tech in stage["techniques"]
    ]
    scores = [score([tech["technique_id"] for stage in row["attack_stages"] for tech in stage["techniques"]], active, pairs) for row in rows]
    base = {tid.split(".")[0] for tid in all_tids}
    return {
        "n": len(rows),
        "unique_active_ids": len(set(all_tids)),
        "unique_base_techniques": len(base),
        "mean_rs": round(sum(scores) / max(1, len(scores)), 6),
        "median_rs": sorted(scores)[len(scores) // 2] if scores else None,
    }


def write_table(result: dict[str, Any]) -> None:
    llm = result.get("llm_reference", {})
    base = result["template_baseline"]
    lines = [
        "% Auto-generated by analysis/non_llm_baseline.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{LLM pipeline versus ATT\\&CK-constrained non-LLM template baseline.}",
        "\\label{tab:non-llm-baseline}",
        "\\small",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Generator & n & Active IDs & Base techniques & Mean $R(S)$ \\\\",
        "\\midrule",
        f"AdverSim LLM & {llm.get('n','--')} & {llm.get('unique_active_ids','--')} & {llm.get('unique_base_techniques','--')} & {llm.get('mean_rs','--')} \\\\",
        f"Template baseline & {base['n']} & {base['unique_active_ids']} & {base['unique_base_techniques']} & {base['mean_rs']} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    TABLE.parent.mkdir(parents=True, exist_ok=True)
    TABLE.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=5150)
    args = parser.parse_args()
    index = load_index()
    rows = generate(args.n, args.seed, index)
    baseline = summarize(rows, index)
    registry = json.loads((ROOT / "results" / "registry.json").read_text(encoding="utf-8")) if (ROOT / "results" / "registry.json").exists() else {}
    llm_reference = {
        "n": registry.get("corpus.scenario_count", {}).get("value"),
        "unique_active_ids": registry.get("corpus.unique_active_v14", {}).get("value"),
        "unique_base_techniques": registry.get("corpus.unique_base_techniques", {}).get("value"),
        "mean_rs": registry.get("realism.full_corpus_mean", {}).get("value"),
    }
    result = {"schema_version": 1, "template_baseline": baseline, "llm_reference": llm_reference}
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    RESULTS.write_text(json.dumps(result, indent=2), encoding="utf-8")
    write_table(result)
    print(f"wrote {RESULTS}")
    print(f"wrote {TABLE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
