"""Add exact binomial CIs and per-technique table for Sigma replay results."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scipy.stats import beta


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "results" / "sigma_measured.json"
OUTPUT = ROOT / "results" / "sigma_replay_intervals.json"
TABLE = ROOT / "paper" / "ieee_access_overleaf" / "table_sigma_replay_by_technique.tex"


def clopper_pearson(k: int, n: int, alpha: float = 0.05) -> list[float]:
    if n == 0:
        return [0.0, 0.0]
    lo = 0.0 if k == 0 else beta.ppf(alpha / 2, k, n - k + 1)
    hi = 1.0 if k == n else beta.ppf(1 - alpha / 2, k + 1, n - k)
    return [round(float(lo), 6), round(float(hi), 6)]


def pct(value: float) -> str:
    return f"{value * 100:.1f}\\%"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT)
    args = parser.parse_args()
    data = json.loads(args.input.read_text(encoding="utf-8"))
    rows = []
    for tid, stats in sorted(data.get("per_technique", {}).items()):
        n = int(stats.get("labelled_events", 0))
        k = int(stats.get("matched_events", 0))
        rows.append({**stats, "technique": tid, "event_match_rate": round(k / max(1, n), 6), "event_match_rate_95ci": clopper_pearson(k, n)})
    detected = sum(1 for row in rows if row["covered"])
    ci = clopper_pearson(detected, len(rows))
    result = {"schema_version": 1, "technique_count": len(rows), "techniques_detected": detected, "technique_coverage_95ci": ci, "per_technique": rows}
    OUTPUT.write_text(json.dumps(result, indent=2), encoding="utf-8")

    lines = [
        "% Auto-generated by analysis/sigma_replay_intervals.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Sigma replay per-technique labelled-event results with exact binomial intervals.}",
        "\\label{tab:sigma-per-technique}",
        "\\small",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Technique & Labelled events & Matched events & Event match rate \\\\",
        "\\midrule",
    ]
    for row in rows:
        lo, hi = row["event_match_rate_95ci"]
        lines.append(f"{row['technique']} & {row['labelled_events']} & {row['matched_events']} & {pct(row['event_match_rate'])} [{pct(lo)}, {pct(hi)}] \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    TABLE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print(f"wrote {TABLE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
