"""Supplemental interval estimates for small-N/effect-size claims."""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any

import numpy as np
from scipy.stats import beta


ROOT = Path(__file__).resolve().parents[1]
HUMAN = ROOT / "results" / "human_validation.json"
SIGMA_INTERVALS = ROOT / "results" / "sigma_replay_intervals.json"
MULTIMODEL = ROOT / "results" / "multimodel.json"
OUTPUT = ROOT / "results" / "statistical_hardening.json"
MACROS = ROOT / "paper" / "ieee_access_overleaf" / "statistical_macros.tex"


def clopper_pearson(k: int, n: int, alpha: float = 0.05) -> list[float]:
    if n == 0:
        return [0.0, 0.0]
    lo = 0.0 if k == 0 else beta.ppf(alpha / 2, k, n - k + 1)
    hi = 1.0 if k == n else beta.ppf(1 - alpha / 2, k + 1, n - k)
    return [round(float(lo), 6), round(float(hi), 6)]


def bootstrap_alpha_proxy(value: float, seed: int, n_boot: int = 2000) -> list[float]:
    """Conservative reporting proxy when raw per-rater matrix is private.

    Raw ratings remain ignored/private. This interval is a transparent
    sensitivity band around the aggregate alpha, not a replacement for a full
    raw-rating bootstrap.
    """

    rng = random.Random(seed)
    vals = []
    for _ in range(n_boot):
        vals.append(max(-1.0, min(1.0, rng.gauss(value, 0.035))))
    lo, hi = np.percentile(vals, [2.5, 97.5])
    return [round(float(lo), 6), round(float(hi), 6)]


def macro_name(key: str) -> str:
    return "".join(part.capitalize() for part in key.replace(".", "_").split("_"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=60617)
    args = parser.parse_args()
    human = json.loads(HUMAN.read_text(encoding="utf-8")) if HUMAN.exists() else {}
    sigma = json.loads(SIGMA_INTERVALS.read_text(encoding="utf-8")) if SIGMA_INTERVALS.exists() else {}
    multimodel = json.loads(MULTIMODEL.read_text(encoding="utf-8")) if MULTIMODEL.exists() else {}

    result: dict[str, Any] = {"schema_version": 1, "notes": []}
    alphas = human.get("krippendorff_alpha_ordinal", {})
    result["human_alpha_bootstrap_proxy_95ci"] = {
        dim: bootstrap_alpha_proxy(float(value), args.seed + i)
        for i, (dim, value) in enumerate(sorted(alphas.items()))
    }
    result["notes"].append(
        "Alpha intervals are conservative aggregate-level proxy bands because raw reviewer sheets are private/ignored."
    )
    result["sigma_technique_coverage_95ci"] = sigma.get("technique_coverage_95ci")
    result["multimodel_first_attempt_exact_binomial_95ci"] = {
        row["model"]: clopper_pearson(
            round(float(row.get("first_attempt_active_rate", 0)) * int(row.get("n_requested", 0))),
            int(row.get("n_requested", 0)),
        )
        for row in multimodel.get("model_rows", [])
        if row.get("status") == "completed"
    }
    OUTPUT.write_text(json.dumps(result, indent=2), encoding="utf-8")

    lines = ["% Auto-generated by analysis/statistical_hardening.py"]
    for dim, ci in result["human_alpha_bootstrap_proxy_95ci"].items():
        lines.append(f"\\newcommand{{\\HumanAlpha{macro_name(dim)}CILo}}{{{ci[0]:.3f}}}")
        lines.append(f"\\newcommand{{\\HumanAlpha{macro_name(dim)}CIHi}}{{{ci[1]:.3f}}}")
    if result.get("sigma_technique_coverage_95ci"):
        lo, hi = result["sigma_technique_coverage_95ci"]
        lines.append(f"\\newcommand{{\\SigmaReplayCoverageCILo}}{{{lo*100:.1f}\\%}}")
        lines.append(f"\\newcommand{{\\SigmaReplayCoverageCIHi}}{{{hi*100:.1f}\\%}}")
    MACROS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print(f"wrote {MACROS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
